from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(850, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(850, 650))
        Dialog.setWindowIcon(QtGui.QIcon('icons/database.png'))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout_1.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")

        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.tableWidget1 = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget1.setAutoFillBackground(False)
        self.tableWidget1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget1.setAlternatingRowColors(True)
        self.tableWidget1.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget1.setRowCount(1)
        self.tableWidget1.setObjectName("tableWidget")
        self.tableWidget1.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        self.tableWidget1.horizontalHeader().setVisible(True)
        self.tableWidget1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget1.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget1.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget1.verticalHeader().setVisible(True)
        self.tableWidget1.verticalHeader().setDefaultSectionSize(35)
        self.tableWidget1.verticalHeader().setHighlightSections(True)
        self.tableWidget1.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout_1.addWidget(self.tableWidget1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_maps = QtWidgets.QLabel()
        self.label_maps.setEnabled(True)
        self.label_maps.setOpenExternalLinks(True)
        self.label_maps.setAlignment(QtCore.Qt.AlignCenter)
        self.label_maps.setObjectName("label_maps")
        self.gridLayout_2.addWidget(self.label_maps, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setWindowTitle(_translate("Dialog", "Image Info"))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item_1 = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "TAGs"))
        item_1.setText(_translate("Dialog", "TAGs"))
        item.setFont(font)
        item_1.setFont(font)

        item = self.tableWidget1.horizontalHeaderItem(1)
        item_1 = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Values"))
        item_1.setText(_translate("Dialog", "Values"))
        item.setFont(font)
        item_1.setFont(font)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "General info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "Exif data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "GPS"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
